-- This migration used to rename indexes/constraints created by
-- 20260523100000_split_product_material_categories, but its timestamp makes it
-- run earlier on a fresh database. Keep the migration as a no-op so existing
-- migration history remains intact; the rename operations now live in the
-- split migration after the referenced relations exist.
