-- 扩展订单状态枚举
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PRODUCTION';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'DELIVERING';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';

-- 鲜花业务与退款字段
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "delivery_date" TEXT NOT NULL DEFAULT '';
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "greeting_card" TEXT;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "delivery_info" TEXT;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "refund_amount" DOUBLE PRECISION;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "refund_time" TIMESTAMP(3);
